# Generated by Django 5.2.3 on 2025-06-24 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('idade', models.PositiveIntegerField()),
                ('altura', models.FloatField(help_text='Em metros')),
                ('peso', models.FloatField(help_text='Em kg')),
                ('percentual_gordura', models.FloatField(blank=True, null=True)),
                ('nivel_atividade', models.CharField(choices=[('1.2', 'Sedentário'), ('1.375', 'Levemente ativo'), ('1.55', 'Moderadamente ativo'), ('1.725', 'Muito ativo'), ('1.9', 'Extremamente ativo')], default='1.2', max_length=5)),
                ('fator_proteina', models.CharField(choices=[('0.8', 'Sedentário'), ('1.2', 'Ativo Leve'), ('1.4', 'Endurance'), ('1.6', 'Força (iniciado)'), ('2.2', 'Força (avançado)')], default='1.2', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PesoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='usuarios.perfil')),
            ],
        ),
    ]
