# Generated by Django 5.2.3 on 2025-06-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fator_proteina',
        ),
    ]
