# Generated by Django 5.2.3 on 2025-06-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_historicopeso_meta_kcal_historicopeso_meta_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopeso',
            name='gordura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel_atividade',
            field=models.CharField(choices=[('baixo', 'Sedentário'), ('moderado', 'Atividade física moderada'), ('alto', 'Atividade física intensa')], default='moderado', max_length=20),
        ),
    ]
