# Generated by Django 5.2.3 on 2025-06-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_historicopeso_gordura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicopeso',
            name='peso_esperado',
            field=models.FloatField(blank=True, help_text='Peso estimado baseado na meta anterior', null=True),
        ),
    ]
